---
- name: OSX Playbook setup
  hosts: localhost
  gather_facts: false

  vars_files:
    - default.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]

  tasks:
    - name: Import tasks for zsh
      ansible.builtin.import_tasks: tasks/oh_my_zsh.yml
      tags: ["oh-my-zsh"]

    - name: Import tasks for dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ["dotfiles"]

    - name: Import tasks for iterm2
      ansible.builtin.import_tasks: tasks/iterm2.yml
      when: configure_iterm2
      tags: ["iterm2"]

    - name: Import tasks for osx
      ansible.builtin.import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ["osx"]
