---
- name: Install Homebrew
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Install Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: (not lookup("pipe","brew --version"))
      tags:
        - homebrew