---
- name: Install VS Code extensions
  collections:
    - community.general
  vscode_extension:
    name: "{{ item }}"
    state: present
  with_items:
    - ms-python.python
    - github.vscode-pull-request-github
    - github.copilot
    - esbenp.prettier-vscode
    - hashicorp.terraform
    - vscode-icons-team.vscode-icons
    - benjaminbenais.copilot-theme
    - github.vscode-github-actions
  tags:
    - vscode-extensions
